/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_mn_z80util_z80_jni_NativeZ80Gateway */

#ifndef _Included_org_mn_z80util_z80_jni_NativeZ80Gateway
#define _Included_org_mn_z80util_z80_jni_NativeZ80Gateway
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_mn_z80util_z80_jni_NativeZ80Gateway
 * Method:    executeNextCommand
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mn_z80util_z80_jni_NativeZ80Gateway_executeNextCommand
  (JNIEnv *, jobject);

/*
 * Class:     org_mn_z80util_z80_jni_NativeZ80Gateway
 * Method:    getReg
 * Signature: (I)B
 */
JNIEXPORT jbyte JNICALL Java_org_mn_z80util_z80_jni_NativeZ80Gateway_getReg
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_mn_z80util_z80_jni_NativeZ80Gateway
 * Method:    getRegPair
 * Signature: (I)S
 */
JNIEXPORT jshort JNICALL Java_org_mn_z80util_z80_jni_NativeZ80Gateway_getRegPair
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_mn_z80util_z80_jni_NativeZ80Gateway
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_mn_z80util_z80_jni_NativeZ80Gateway_reset
  (JNIEnv *, jobject);

/*
 * Class:     org_mn_z80util_z80_jni_NativeZ80Gateway
 * Method:    setHaltState
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_mn_z80util_z80_jni_NativeZ80Gateway_setHaltState
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     org_mn_z80util_z80_jni_NativeZ80Gateway
 * Method:    setReg
 * Signature: (IB)V
 */
JNIEXPORT void JNICALL Java_org_mn_z80util_z80_jni_NativeZ80Gateway_setReg
  (JNIEnv *, jobject, jint, jbyte);

/*
 * Class:     org_mn_z80util_z80_jni_NativeZ80Gateway
 * Method:    setRegPair
 * Signature: (IS)V
 */
JNIEXPORT void JNICALL Java_org_mn_z80util_z80_jni_NativeZ80Gateway_setRegPair
  (JNIEnv *, jobject, jint, jshort);

#ifdef __cplusplus
}
#endif
#endif
